version: "3.9"
services:
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      # AMQP protocol port
      - "5672:5672"
      # Management UI
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
  # apps:
  #   container_name: my-app
  #   build: 
  #     context: ./apps
  #     dockerfile: Dockerfile.dev
  #   restart: always
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - ./apps/src:/app/src
  api-gateway:
    container_name: gateway
    build:
      context: ./package/api-gateway
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    env_file: ./package/api-gateway/configs/.env
    volumes:
      - ./package/api-gateway/src:/app/src
    environment:
      # OUTSOURCE SERVICE
      - AUTH_SERVICE_URL=http://auth:3001
      - NOTIFICATION_SERVICE_URL=http://notification:3002
      - USER_SERVICE_URL=http://user:3003
      - EVENT_SERVICE=http://event:3004
      - APPLICATION_SERVICE_URL=http://application:3005
      - CLIENT_URL = http://localhost:9000
  auth:
    container_name: auth
    build:
      context: ./package/auth
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3001:3001
    env_file: ./package/auth/configs/.env
    volumes:
      - ./package/auth/src:/app/src
    depends_on:
      rabbitmq:
        condition: service_healthy
  user:
    container_name: user
    build:
      context: ./package/user
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3003:3003
    env_file: ./package/user/configs/.env
    volumes:
      - ./package/user/src:/app/src
  notification:
    container_name: notification
    build:
      context: ./package/notification
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3002:3002
    env_file: ./package/notification/configs/.env
    volumes:
      - ./package/notification/src:/app/src
    environment:
      - RABBITMQ_ENDPOINT=amqp://myuser:mypassword@rabbitmq_container:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
  event:
    container_name: event
    build:
      context: ./package/event
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3004:3004
    volumes:
      - ./package/event/src:/app/src
  application:
    container_name: application
    build:
      context: ./package/application
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3005:3005
    env_file: ./package/application/configs/.env
    volumes:
      - ./package/application/src:/app/src
networks:
  default:
    driver: bridge
